### ISSUE TITLE
errou ao rodar o projeto

### ISSUE THREAD

**Issue by renatogsmello** [brassagem-forte/bjcp-score#1]
![image](https://user-images.githubusercontent.com/25161706/111215180-9e82a600-85b1-11eb-9317-33b80728508a.png)

Como devo proceder? tenho que ter um Db local?

**Comment by renatogsmello** [comment]
Resolvido!

**Comment by henriqueboaventura** [comment]
Acabei atualizando o README.md para ser mais completo o passo a passo para rodar usando sqlite :)
